import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-screen h-screen flex flex-col justify-center items-center gap-4'>
        <h1 
        className='font-bold text-3xl' 
        >🚧 Em desenvolvimento 🚧</h1>
        <Link 
        href="/app" 
        className='px-5 py-2 bg-zinc-900 text-white rounded-md' 
        >ir para app</Link>
      </main>
    </>
  )
}
